#include "clar_libgit2.h"
#include "pathspec_helpers.h"

/**
 * Same fixture as revwalk::pathspec, but with a commit-graph generated by
 * `git commit-graph write --reachable --changed-paths`, so it carries real
 * changed-path Bloom filters. The commit history and OIDs are identical to
 * testrepo.git; only the derived commit-graph differs. These tests reuse
 * the exact same expectations (from pathspec_helpers) to confirm the
 * Bloom-filter fast path in git_revwalk_next() never disagrees with the
 * pathspec tree-diff fallback.
 */
static git_repository *repo;

void test_revwalk_pathspec_bloom__initialize(void)
{
	repo = cl_git_sandbox_init("testrepo_bloom.git");
}

void test_revwalk_pathspec_bloom__cleanup(void)
{
	cl_git_sandbox_cleanup();
}

void test_revwalk_pathspec_bloom__cases(void)
{
	pathspec_run_cases(repo);
}
